// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WashingCar_DAL.Data;

#nullable disable

namespace WashingCar_DAL.Migrations
{
    [DbContext(typeof(WashingCarDbContext))]
    [Migration("20260824191056_AddServiceVehiclePricing")]
    partial class AddServiceVehiclePricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WashingCar_DAL.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.HasIndex(new[] { "CreatedAtUtc" }, "IX_AuditLog_CreatedAtUtc")
                        .IsDescending();

                    b.HasIndex(new[] { "TableName", "RecordId" }, "IX_AuditLog_Table_Record");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditLog_UserId")
                        .HasFilter("([UserId] IS NOT NULL)");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("BookingDiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BookingFinalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte>("BookingStatus")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("BookingSubtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte>("BookingType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckInAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CheckInQrCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CheckedInByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("int");

                    b.Property<int>("RedeemedPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReminderSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SlotInventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserVoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VehicleConditionAtBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VehicleSurchargeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("VehicleSurchargeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9, 4)")
                        .HasDefaultValue(0m);

                    b.HasKey("BookingId");

                    b.HasIndex(new[] { "AssignedStaffId" }, "IX_Booking_AssignedStaffId")
                        .HasFilter("([AssignedStaffId] IS NOT NULL)");

                    b.HasIndex(new[] { "BranchId" }, "IX_Booking_BranchId");

                    b.HasIndex(new[] { "CheckedInByUserId" }, "IX_Booking_CheckedInByUserId")
                        .HasFilter("([CheckedInByUserId] IS NOT NULL)");

                    b.HasIndex(new[] { "SlotInventoryId" }, "IX_Booking_SlotInventoryId");

                    b.HasIndex(new[] { "BookingStatus", "CreatedAtUtc" }, "IX_Booking_Status_CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId" }, "IX_Booking_UserId");

                    b.HasIndex(new[] { "VehicleId" }, "IX_Booking_VehicleId");

                    b.HasIndex(new[] { "BookingCode" }, "UQ_Booking_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "CheckInQrCode" }, "UQ_Booking_QrCode")
                        .IsUnique();

                    b.HasIndex(new[] { "UserVoucherId" }, "UX_Booking_UserVoucherId")
                        .IsUnique()
                        .HasFilter("([UserVoucherId] IS NOT NULL)");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.BookingLine", b =>
                {
                    b.Property<Guid>("BookingLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("BookingLineId");

                    b.HasIndex(new[] { "BookingId" }, "IX_BookingLine_BookingId");

                    b.HasIndex(new[] { "ServiceCatalogItemId" }, "IX_BookingLine_ServiceCatalogItemId");

                    b.ToTable("BookingLine", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Branch", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("BranchId");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "BranchCode" }, "UQ_Branch_Code")
                        .IsUnique();

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.BranchService", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BranchId", "ServiceCatalogItemId");

                    b.HasIndex("ServiceCatalogItemId");

                    b.ToTable("BranchService", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.LoyaltyAccount", b =>
                {
                    b.Property<Guid>("LoyaltyAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoyaltyAccountId");

                    b.HasIndex(new[] { "TierId" }, "IX_LoyaltyAccount_TierId");

                    b.HasIndex(new[] { "UserId" }, "UQ_LoyaltyAccount_User")
                        .IsUnique();

                    b.ToTable("LoyaltyAccount", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.LoyaltyLedgerEntry", b =>
                {
                    b.Property<Guid>("LoyaltyLedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("EntryType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("LoyaltyAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoyaltyLedgerEntryId");

                    b.HasIndex(new[] { "BookingId" }, "IX_LLE_BookingId")
                        .HasFilter("([BookingId] IS NOT NULL)");

                    b.HasIndex(new[] { "LoyaltyAccountId", "CreatedAtUtc" }, "IX_LLE_LoyaltyAccount_Created")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId" }, "IX_LLE_UserId");

                    b.ToTable("LoyaltyLedgerEntry", null, t =>
                        {
                            t.HasTrigger("trg_LLE_AfterInsert_RecomputeTier");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("OriginalPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentType")
                        .HasColumnType("tinyint");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RefundedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("RefundedByUserId");

                    b.HasIndex(new[] { "BookingId" }, "IX_Payment_BookingId");

                    b.HasIndex(new[] { "OriginalPaymentId" }, "IX_Payment_OriginalPaymentId")
                        .HasFilter("([OriginalPaymentId] IS NOT NULL)");

                    b.HasIndex(new[] { "PaymentStatus", "CreatedAtUtc" }, "IX_Payment_Status_CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex(new[] { "UserId" }, "IX_RefreshToken_UserId");

                    b.HasIndex(new[] { "Token" }, "UQ_RefreshToken_Token")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReviewType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("ReviewType");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex(new[] { "StaffId" }, "IX_Review_StaffId")
                        .HasFilter("([StaffId] IS NOT NULL)");

                    b.HasIndex(new[] { "UserId" }, "IX_Review_UserId");

                    b.HasIndex(new[] { "BookingId", "ReviewType" }, "UQ_Review_Booking_Type")
                        .IsUnique();

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.ServiceCatalogItem", b =>
                {
                    b.Property<Guid>("ServiceCatalogItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("ParentServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("SelectionMode")
                        .HasColumnType("tinyint");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("ServiceNodeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<byte>("ServicePackageType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("ServiceCatalogItemId");

                    b.HasIndex("ParentServiceCatalogItemId")
                        .HasDatabaseName("IX_ServiceCatalogItem_ParentServiceCatalogItemId");

                    b.ToTable("ServiceCatalogItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceCatalogItem_GroupBillingFields", "([ServiceNodeType] = 1 AND [BasePrice] = 0 AND [DurationMinutes] = 0) OR [ServiceNodeType] = 2");

                            t.HasCheckConstraint("CK_ServiceCatalogItem_GroupSelectionMode", "([ServiceNodeType] = 1 AND [SelectionMode] = 1) OR ([ServiceNodeType] = 2 AND [SelectionMode] IS NULL)");

                            t.HasCheckConstraint("CK_ServiceCatalogItem_ServiceNodeType", "[ServiceNodeType] IN (1, 2)");

                            t.HasCheckConstraint("CK_ServiceCatalogItem_ServicePackageType", "[ServicePackageType] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.ServiceVehiclePricing", b =>
                {
                    b.Property<Guid>("ServiceVehiclePricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("EngineCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("ServiceVehiclePricingId");

                    b.HasIndex("EngineCatalogId");

                    b.HasIndex("ServiceCatalogItemId", "VehicleType")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceVehiclePricing_DefaultScope")
                        .HasFilter("[EngineCatalogId] IS NULL");

                    b.HasIndex("ServiceCatalogItemId", "VehicleType", "EngineCatalogId")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceVehiclePricing_ExactScope")
                        .HasFilter("[EngineCatalogId] IS NOT NULL");

                    b.ToTable("ServiceVehiclePricing", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceVehiclePricing_DurationMinutes", "[DurationMinutes] > 0");

                            t.HasCheckConstraint("CK_ServiceVehiclePricing_UnitPrice", "[UnitPrice] > 0");

                            t.HasCheckConstraint("CK_ServiceVehiclePricing_VehicleType", "[VehicleType] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.SlotInventory", b =>
                {
                    b.Property<Guid>("SlotInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<short>("OnlineReservedCount")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time");

                    b.Property<short>("WalkInReservedCount")
                        .HasColumnType("smallint");

                    b.HasKey("SlotInventoryId");

                    b.HasIndex(new[] { "BranchId" }, "IX_SlotInventory_BranchId");

                    b.HasIndex(new[] { "SlotDate" }, "IX_SlotInventory_SlotDate");

                    b.HasIndex(new[] { "BranchId", "SlotDate", "SlotStartTime" }, "UQ_SlotInventory_Branch_DateTime")
                        .IsUnique();

                    b.ToTable("SlotInventory", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.TenderAllocation", b =>
                {
                    b.Property<Guid>("TenderAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("TenderType")
                        .HasColumnType("tinyint");

                    b.HasKey("TenderAllocationId");

                    b.HasIndex(new[] { "PaymentId" }, "IX_TenderAllocation_PaymentId");

                    b.ToTable("TenderAllocation", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Tier", b =>
                {
                    b.Property<Guid>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Benefits")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("EarnRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TierId");

                    b.HasIndex(new[] { "MinPoints" }, "UQ_Tier_MinPoints")
                        .IsUnique();

                    b.HasIndex(new[] { "TierName" }, "UQ_Tier_TierName")
                        .IsUnique();

                    b.ToTable("Tier", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.TierBenefit", b =>
                {
                    b.Property<Guid>("TierBenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<byte>("BenefitType")
                        .HasColumnType("tinyint");

                    b.Property<string>("BenefitValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("TierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TierBenefitId");

                    b.HasIndex(new[] { "TierId", "BenefitType" }, "UQ_TierBenefit_Tier_Type")
                        .IsUnique();

                    b.ToTable("TierBenefit", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.TierVoucher", b =>
                {
                    b.Property<Guid>("TierVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TierVoucherId");

                    b.HasIndex(new[] { "VoucherId" }, "IX_TierVoucher_VoucherId");

                    b.HasIndex(new[] { "TierId", "VoucherId" }, "UQ_TierVoucher_Pair")
                        .IsUnique();

                    b.ToTable("TierVoucher", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("UserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex(new[] { "BranchId" }, "IX_User_BranchId")
                        .HasFilter("([BranchId] IS NOT NULL)");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_User_PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UX_User_Email")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL AND [IsDeleted]=(0))");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.UserVoucher", b =>
                {
                    b.Property<Guid>("UserVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("RedeemedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RedeemedPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VoucherStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("UserVoucherId");

                    b.HasIndex(new[] { "UserId", "VoucherStatus" }, "IX_UserVoucher_UserId_Status");

                    b.HasIndex(new[] { "VoucherId" }, "IX_UserVoucher_VoucherId");

                    b.ToTable("UserVoucher", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<byte?>("BodyStyle")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("BodyStyleCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("BrandCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EngineCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("EngineType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("VehicleId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex(new[] { "BodyStyleCatalogId" }, "IX_Vehicle_BodyStyleCatalogId");

                    b.HasIndex(new[] { "BrandCatalogId" }, "IX_Vehicle_BrandCatalogId");

                    b.HasIndex(new[] { "EngineCatalogId" }, "IX_Vehicle_EngineCatalogId");

                    b.HasIndex(new[] { "UserId" }, "IX_Vehicle_UserId");

                    b.HasIndex(new[] { "LicensePlate" }, "UX_Vehicle_LicensePlate")
                        .IsUnique()
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleBodyStyleCatalog", b =>
                {
                    b.Property<Guid>("VehicleBodyStyleCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte?>("LegacyEnumValue")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("VehicleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.HasKey("VehicleBodyStyleCatalogId");

                    b.HasIndex(new[] { "VehicleType" }, "IX_VehicleBodyStyleCatalog_VehicleType");

                    b.HasIndex(new[] { "Code" }, "UQ_VehicleBodyStyleCatalog_Code")
                        .IsUnique();

                    b.ToTable("VehicleBodyStyleCatalog", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleBrandCatalog", b =>
                {
                    b.Property<Guid>("VehicleBrandCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLuxury")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("VehicleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.HasKey("VehicleBrandCatalogId");

                    b.HasIndex(new[] { "VehicleType" }, "IX_VehicleBrandCatalog_VehicleType");

                    b.HasIndex(new[] { "Code" }, "UQ_VehicleBrandCatalog_Code")
                        .IsUnique();

                    b.ToTable("VehicleBrandCatalog", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleEngineCatalog", b =>
                {
                    b.Property<Guid>("VehicleEngineCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte?>("LegacyEnumValue")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("VehicleEngineCatalogId");

                    b.HasIndex(new[] { "Code" }, "UQ_VehicleEngineCatalog_Code")
                        .IsUnique();

                    b.ToTable("VehicleEngineCatalog", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleImage", b =>
                {
                    b.Property<Guid>("VehicleImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VehicleImageId");

                    b.HasIndex(new[] { "VehicleId" }, "IX_VehicleImage_VehicleId");

                    b.HasIndex(new[] { "VehicleId" }, "UX_VehicleImage_Primary")
                        .IsUnique()
                        .HasFilter("([IsPrimary]=(1))");

                    b.ToTable("VehicleImage", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Voucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<byte>("ApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DiscountType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("VoucherType")
                        .HasColumnType("tinyint");

                    b.HasKey("VoucherId");

                    b.HasIndex(new[] { "IsActive", "StartUtc", "EndUtc" }, "IX_Voucher_Active_DateRange")
                        .HasFilter("([IsActive]=(1))");

                    b.HasIndex(new[] { "ApprovedByUserId" }, "IX_Voucher_ApprovedByUserId");

                    b.HasIndex(new[] { "BranchId" }, "IX_Voucher_BranchId")
                        .HasFilter("[BranchId] IS NOT NULL");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Voucher_CreatedByUserId");

                    b.HasIndex(new[] { "VoucherCode" }, "UQ_Voucher_Code")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Booking", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.User", "AssignedStaff")
                        .WithMany("BookingAssignedStaffs")
                        .HasForeignKey("AssignedStaffId")
                        .HasConstraintName("FK_Booking_AssignedStaff");

                    b.HasOne("WashingCar_DAL.Entities.Branch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Branch");

                    b.HasOne("WashingCar_DAL.Entities.User", "CheckedInByUser")
                        .WithMany("BookingCheckedInByUsers")
                        .HasForeignKey("CheckedInByUserId")
                        .HasConstraintName("FK_Booking_CheckedInBy");

                    b.HasOne("WashingCar_DAL.Entities.SlotInventory", "SlotInventory")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotInventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Slot");

                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("BookingUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_User");

                    b.HasOne("WashingCar_DAL.Entities.UserVoucher", "UserVoucher")
                        .WithOne("Booking")
                        .HasForeignKey("WashingCar_DAL.Entities.Booking", "UserVoucherId")
                        .HasConstraintName("FK_Booking_UserVoucher");

                    b.HasOne("WashingCar_DAL.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Vehicle");

                    b.Navigation("AssignedStaff");

                    b.Navigation("Branch");

                    b.Navigation("CheckedInByUser");

                    b.Navigation("SlotInventory");

                    b.Navigation("User");

                    b.Navigation("UserVoucher");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.BookingLine", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Booking", "Booking")
                        .WithMany("BookingLines")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingLine_Booking");

                    b.HasOne("WashingCar_DAL.Entities.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany("BookingLines")
                        .HasForeignKey("ServiceCatalogItemId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingLine_Service");

                    b.Navigation("Booking");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Branch", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Branch_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.BranchService", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Branch", "Branch")
                        .WithMany("BranchServices")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BranchService_Branch");

                    b.HasOne("WashingCar_DAL.Entities.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany("BranchServices")
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BranchService_Service");

                    b.Navigation("Branch");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.LoyaltyAccount", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Tier", "Tier")
                        .WithMany("LoyaltyAccounts")
                        .HasForeignKey("TierId")
                        .IsRequired()
                        .HasConstraintName("FK_LoyaltyAccount_Tier");

                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithOne("LoyaltyAccount")
                        .HasForeignKey("WashingCar_DAL.Entities.LoyaltyAccount", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LoyaltyAccount_User");

                    b.Navigation("Tier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.LoyaltyLedgerEntry", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Booking", "Booking")
                        .WithMany("LoyaltyLedgerEntries")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_LLE_Booking");

                    b.HasOne("WashingCar_DAL.Entities.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("LoyaltyLedgerEntries")
                        .HasForeignKey("LoyaltyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_LLE_LoyaltyAccount");

                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("LoyaltyLedgerEntries")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LLE_User");

                    b.Navigation("Booking");

                    b.Navigation("LoyaltyAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Payment", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Booking");

                    b.HasOne("WashingCar_DAL.Entities.Payment", "OriginalPayment")
                        .WithMany("InverseOriginalPayment")
                        .HasForeignKey("OriginalPaymentId")
                        .HasConstraintName("FK_Payment_Original");

                    b.HasOne("WashingCar_DAL.Entities.User", "RefundedByUser")
                        .WithMany("Payments")
                        .HasForeignKey("RefundedByUserId")
                        .HasConstraintName("FK_Payment_RefundedBy");

                    b.Navigation("Booking");

                    b.Navigation("OriginalPayment");

                    b.Navigation("RefundedByUser");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Review", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Review_Booking");

                    b.HasOne("WashingCar_DAL.Entities.User", "Staff")
                        .WithMany("ReviewStaffs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_Review_Staff");

                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Review_User");

                    b.Navigation("Booking");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.ServiceCatalogItem", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.ServiceCatalogItem", "ParentServiceCatalogItem")
                        .WithMany("ChildServiceCatalogItems")
                        .HasForeignKey("ParentServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ServiceCatalogItem_Parent");

                    b.Navigation("ParentServiceCatalogItem");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.ServiceVehiclePricing", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.VehicleEngineCatalog", "EngineCatalog")
                        .WithMany("ServiceVehiclePricings")
                        .HasForeignKey("EngineCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ServiceVehiclePricing_EngineCatalog");

                    b.HasOne("WashingCar_DAL.Entities.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany("ServiceVehiclePricings")
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceVehiclePricing_Service");

                    b.Navigation("EngineCatalog");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.SlotInventory", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Branch", "Branch")
                        .WithMany("SlotInventories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SlotInventory_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.TenderAllocation", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Payment", "Payment")
                        .WithMany("TenderAllocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TA_Payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.TierBenefit", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Tier", "Tier")
                        .WithMany("TierBenefits")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TierBenefit_Tier");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.TierVoucher", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Tier", "Tier")
                        .WithMany("TierVouchers")
                        .HasForeignKey("TierId")
                        .IsRequired()
                        .HasConstraintName("FK_TierVoucher_Tier");

                    b.HasOne("WashingCar_DAL.Entities.Voucher", "Voucher")
                        .WithMany("TierVouchers")
                        .HasForeignKey("VoucherId")
                        .IsRequired()
                        .HasConstraintName("FK_TierVoucher_Voucher");

                    b.Navigation("Tier");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.User", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Branch", "Branch")
                        .WithMany("Staff")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_User_Branch");

                    b.HasOne("WashingCar_DAL.Entities.User", "DeletedByUser")
                        .WithMany("InverseDeletedByUser")
                        .HasForeignKey("DeletedByUserId")
                        .HasConstraintName("FK_User_DeletedBy");

                    b.Navigation("Branch");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.UserVoucher", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserVoucher_User");

                    b.HasOne("WashingCar_DAL.Entities.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .IsRequired()
                        .HasConstraintName("FK_UserVoucher_Voucher");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Vehicle", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.VehicleBodyStyleCatalog", "BodyStyleCatalog")
                        .WithMany("Vehicles")
                        .HasForeignKey("BodyStyleCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Vehicle_BodyStyleCatalog");

                    b.HasOne("WashingCar_DAL.Entities.VehicleBrandCatalog", "BrandCatalog")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Vehicle_BrandCatalog");

                    b.HasOne("WashingCar_DAL.Entities.User", "DeletedByUser")
                        .WithMany("VehicleDeletedByUsers")
                        .HasForeignKey("DeletedByUserId")
                        .HasConstraintName("FK_Vehicle_DeletedBy");

                    b.HasOne("WashingCar_DAL.Entities.VehicleEngineCatalog", "EngineCatalog")
                        .WithMany("Vehicles")
                        .HasForeignKey("EngineCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Vehicle_EngineCatalog");

                    b.HasOne("WashingCar_DAL.Entities.User", "User")
                        .WithMany("VehicleUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_User");

                    b.Navigation("BodyStyleCatalog");

                    b.Navigation("BrandCatalog");

                    b.Navigation("DeletedByUser");

                    b.Navigation("EngineCatalog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleImage", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VehicleImage_Vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Voucher", b =>
                {
                    b.HasOne("WashingCar_DAL.Entities.User", "ApprovedByUser")
                        .WithMany("VoucherApprovedByUsers")
                        .HasForeignKey("ApprovedByUserId")
                        .HasConstraintName("FK_Voucher_ApprovedBy");

                    b.HasOne("WashingCar_DAL.Entities.Branch", "Branch")
                        .WithMany("Vouchers")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Voucher_Branch");

                    b.HasOne("WashingCar_DAL.Entities.User", "CreatedByUser")
                        .WithMany("VoucherCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Voucher_CreatedBy");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Booking", b =>
                {
                    b.Navigation("BookingLines");

                    b.Navigation("LoyaltyLedgerEntries");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Branch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BranchServices");

                    b.Navigation("SlotInventories");

                    b.Navigation("Staff");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.LoyaltyAccount", b =>
                {
                    b.Navigation("LoyaltyLedgerEntries");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Payment", b =>
                {
                    b.Navigation("InverseOriginalPayment");

                    b.Navigation("TenderAllocations");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.ServiceCatalogItem", b =>
                {
                    b.Navigation("BookingLines");

                    b.Navigation("BranchServices");

                    b.Navigation("ChildServiceCatalogItems");

                    b.Navigation("ServiceVehiclePricings");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.SlotInventory", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Tier", b =>
                {
                    b.Navigation("LoyaltyAccounts");

                    b.Navigation("TierBenefits");

                    b.Navigation("TierVouchers");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BookingAssignedStaffs");

                    b.Navigation("BookingCheckedInByUsers");

                    b.Navigation("BookingUsers");

                    b.Navigation("InverseDeletedByUser");

                    b.Navigation("LoyaltyAccount");

                    b.Navigation("LoyaltyLedgerEntries");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewStaffs");

                    b.Navigation("Reviews");

                    b.Navigation("UserVouchers");

                    b.Navigation("VehicleDeletedByUsers");

                    b.Navigation("VehicleUsers");

                    b.Navigation("VoucherApprovedByUsers");

                    b.Navigation("VoucherCreatedByUsers");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.UserVoucher", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("VehicleImages");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleBodyStyleCatalog", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleBrandCatalog", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.VehicleEngineCatalog", b =>
                {
                    b.Navigation("ServiceVehiclePricings");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("WashingCar_DAL.Entities.Voucher", b =>
                {
                    b.Navigation("TierVouchers");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
